### ISSUE TITLE
[DNS劫持]shadowrocket配置方法

### ISSUE THREAD

**Issue by AndyKong2020** [BeiyanYunyi/totoroschool-autorun#10]
你好，我在shadowrocket上配置hosts，添加域名https://xtotoro.com  映射到我运行工程的电脑的ip，位于同一局域网下且已经运行显示  
```
将由学号生成 MAC 地址
请在 iOS 设备上完成登录流程
```
但在safari上https://xtotoro.com  显示Whitelabel Error Page页面  。
在safari输入电脑ip加上端口11451）可以进入"欢迎使用艹猫校园"页面，我也尝试在host映射中加上端口号，但并没有解决问题。
请问是我的配置方式哪里除了问题，若能帮助解答不胜感激

**Comment by BeiyanYunyi** [comment]
https://github.com/BeiyanYunyi/totoro-paradise

不用劫持了，也不用 iOS 了（）

**Comment by AndyKong2020** [comment]
哇居然写了新的，感谢感谢，大佬能否教教怎么用，或者写个readme（），我没学过前端太菜了。。

**Comment by BeiyanYunyi** [comment]
1. 装 Node.js （要求>16，推荐18）
2. 输入 `corepack enable` 命令
3. 在 clone 下来的文件夹下，执行 `pnpm i`
4. 在 clone 下来的文件夹下，执行 `pnpm dev`
5. 访问 `http://localhost:3000`，并按网页指引操作

**Comment by AndyKong2020** [comment]
十分有幫助，star了
